config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show]

  root 'static_pages#home'

  resources :posts, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order('created_at DESC') }
  validates :user_id, presence: true

  def self.from_users_followed_by(user)
    followed_user_ids = "SELECT followed_id FROM relationships
                         WHERE follower_id = :user_id"
    where("user_id IN (#{followed_user_ids}) OR user_id = :user_id",
          user_id: user.id)
  end
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :posts, dependent: :destroy
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed
  has_many :reverse_relationships, foreign_key: "followed_id",
                                   class_name:  "Relationship",
                                   dependent:   :destroy
  has_many :followers, through: :reverse_relationships, source: :follower

  def follow!(other_user)
    relationships.create(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    relationships.find_by(followed_id: other_user.id)
  end

  def feed
    Post.from_users_followed_by(self)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(micropost_params)
    if @post.save
      flash[:success] = "Post created!"
      redirect_to root_url
    else
      # @feed_items = []
      render 'static_pages/home'
    end
  end

  def destroy
    @post = Post.find_by_id(params[:id])
    @post.destroy
    flash[:success] = "You have deleted your post."
    redirect_to root_url
  end

  private

    def micropost_params
      params.require(:post).permit(:title, :content)
    end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    @user = User.find(params[:format])
    current_user.follow!(@user)

    redirect_to user_path(@user)
  end

  def destroy
    @user = User.find(params[:id])
    current_user.unfollow!(@user)

    redirect_to user_path(@user)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if user_signed_in?
      @posts = current_user.feed
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by_id(params[:id])
    @posts = @user.posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Fumblr", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "New Post", new_post_path %></li>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: "delete" %></li>
          <li><%= link_to "Edit Account", edit_user_registration_path(current_user) %></li>
          <li><%= link_to "Profile", user_path(current_user) %></li>
        <% else %>
          <li><%= link_to "Sign In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></a></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fumblr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/posts/_post.html.erb
<div class="row">
  <% if user_signed_in? && post.user_id == current_user.id %>
  <div class="col-xs-10">
  <% else %>
  <div class="col-xs-12">
  <% end %>
    <h2><%= post.title %></h2>
    <p><%= post.content %></p>
    <small><%= link_to post.created_at.to_time.strftime('%b %e at %I %M %p'), user_path(post.user_id) %></small>
  </div>
  <% if user_signed_in? && post.user_id == current_user.id %>
    <div class="col-xs-2 text-right">
      <%= link_to "<i class=\"fa fa-trash\"></i>".html_safe, post_path(post), method: "delete" %>
    </div>
  <% end %>
</div>
<hr>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/new.html.erb
<h1>Create Post</h1>
<%= simple_form_for(@post, html: { class: 'form-horizontal' }) do |f| %>
  <%= f.input :title %>
  <%= f.input :content %>
  <%= f.button :submit %>
<% end %>

app/views/static_pages/home.html.erb
<h1 class="header">Welcome to Fumblr!</h1>
<% if user_signed_in? %>
  <%= "Hello #{current_user.email}" %>
  <%= render @posts %>
<% else %>
  <p><%= link_to "Sign In", new_user_session_path %> or <%= link_to "Sign Up", new_user_registration_path %> to follow users and post!</p>
<% end %>

app/views/users/show.html.erb
<div class="row">
  <div class="col-xs-10">
    <h1><%= @user.email %>'s posts</h1>
  </div>
  <div class="col-xs-2 text-right">
    <% if user_signed_in? && !current_user.following?(@user) && @user != current_user %>
      <h1><%= link_to "Follow", relationships_path(@user.id), class: "btn btn-primary", method: "post" %></h1>
    <% elsif user_signed_in? && current_user.following?(@user) %>
      <h1><%= link_to "Unfollow", relationship_path(@user), class: "btn btn-primary", method: "delete" %></h1>
    <% end %>
  </div>  
</div>

<%= render @posts %>